### PR TITLE
Clarify where redirects should go.

### PR DESCRIPTION
**Pull request by mateusz**
Take "public" dir into account.

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks @mateusz. Do you think it's also worth calling out the differences between RedirectRule and RedirectMatch?

**Comment by mateusz** [comment]
@michalkleiner I personally feel like we don't want to repeat apache docs here. This behaviour isn't really related to CWP, and it's the implementer's responsibility to understand how it works.

Now, making it clearer where is the webroot pointed to *is* CWP related, and has a bearing on this, so I think this particular piece of information could be exposed somewhere.

Any suggestions as to good location? Inline here, and in htaccess docs?

**Comment by michalkleiner** [comment]
@mateusz maybe under https://www.cwp.govt.nz/developer-docs/en/2/working_with_projects/infrastructural_considerations/#webserver-2 ?

**Comment by mateusz** [comment]
@michalkleiner care to review? Change in green:

---

Screen Shot 2020-07-13 at 12 03 22 PM

**Comment by michalkleiner** [comment]
@mateusz that reads ok, thanks. Keeping the recipe's .htaccess file verbatim is not for _security reasons_ though — it's a functional necessity, not a security measure.

I've also made a PR for the actual .htaccess to support this 
https://github.com/silverstripe/cwp/pull/284/files — happy to adjust the wording there a bit to align with your change in the docs.

**Comment by mateusz** [comment]
True, removed the remark about security reasons, and merged, thanks for review!
I saw your other PR - let's move over there.

**Pull request merged**
