### PR TITLE
Update realme_authentication.md

### PR DESCRIPTION
**Pull request by JessicaSilverStripe**
The RealMe team (via Kayleigh at DIA) have requested changes to the text displaying on https://www.cwp.govt.nz/developer-docs/en/2/features/realme_authentication/.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Hey Jessica. Thanks for the update. There's some markdown formatting issues at the moment that'll need to be fixed up: https://github.com/silverstripe/cwp/blob/1ac2fb71b512dbb3d443b58852ea24c225e030d1/docs/en/02_Features/realme_authentication.md

**Comment by ScopeyNZ** [comment]
Additionally we might want to adjust the note that the module is supported from `1.2` onwards. I think we really only support from `2.0` now? Better double check that with @madmatt but I assume we definitely don't want to patch the `1` branch.

**Comment by madmatt** [comment]
Thanks for the pull request Jessica!

To address Guy's point, we could say "You must be using CWP Recipe 1.2.0 or higher to use the module, however we strongly recommend using the most recent version of the module at all times."

Thoughts on that? I want to stay away from specific version numbers like `1.9` or `2.0`, because they'll only get out of date (and partly because it's confusing because you're talking about CWP recipe versions, not RealMe module versions).

**Comment by JessicaSilverStripe** [comment]
Thanks Matt & Guy. I've changed the "1.2..." text to be " We strongly recommend using the most recent version of the module."

**Pull request merged**
