### PR TITLE
DOCS Update HTTP Caching docs

### PR DESCRIPTION
**Pull request by dhensby**
backport of #108

### CODE REVIEW

**Comment by dhensby** [comment]
do we need to bump [cwp-core](https://github.com/silverstripe/cwp-core):1.9 to `silverstripe/framework:^3.7` ?

**Comment by chillu** [comment]
> do we need to bump cwp-core:1.9 to silverstripe/framework:^3.7 ?

@robbieaverill I suppose so? Guess those constraints are dictated by the recipe, which can be higher than cwp-core. Is there a process in place for syncing up those constraints across modules? I'm not too fussed either way - and in this particular case, I don't think that updating the docs would strictly mandate a constraint change. That would only be necessary if you start using new APIs in code.

**Comment by robbieaverill** [comment]
Yep you're right - if the CWP core module is using APIs in 3.7 then we should update that constraint, but otherwise it's handled by the recipes. It wouldn't hurt to update it anyway though if somebody wants to do it, but it's not normally something we'd bump unless the code requires it

**Comment by dhensby** [comment]
Hmm, OK - it's just I'm making reference to "in 1.9+" when actually, it's not it's in SS 3.7+, should that be changed? Are CWP devs across the distinction?

**Comment by chillu** [comment]
Given that CWP dev docs are structured the same way as doc.silverstripe.org, and only pull in the latest SHA of the release branch (rather than a tagged release), I think the distinction doesn't matter too much in practice.

**Comment by chillu** [comment]
Merging, see rationale in https://github.com/silverstripe/cwp/pull/108#issuecomment-407901970

**Pull request merged**
